from enum import Enum

class SfeType(Enum):
    CMD_AMBIENT_SETPOINT = 'SFE_Cmd_AmbientSetpoint'
    CMD_FAN_MODE = 'SFE_Cmd_FanMode'
    CMD_FAN_SPEED = 'SFE_Cmd_FanSpeed'
    CMD_FAN_SPEED_3V = 'SFE_Cmd_FanSpeed3V'
    CMD_FORCED_ONTIME = 'SFE_Cmd_ForcedOnTime'
    CMD_HVAC_MODE = 'SFE_Cmd_HVACMode'
    CMD_LOAD_TIMED = 'SFE_Cmd_LoadTimed'
    CMD_ON_OFF = 'SFE_Cmd_OnOff'
    CMD_SHUTTER = 'SFE_Cmd_Shutter'
    CMD_TIMED_DYNAMIC_MODE = 'SFE_Cmd_TimedDynamicMode'
    CMD_TIMED_MANUAL = 'SFE_Cmd_TimedManual'
    STATE_AMBIENT_SETPOINT = 'SFE_State_AmbientSetpoint'
    STATE_AMBIENT_TEMPERATURE = 'SFE_State_AmbientTemperature'
    STATE_CHANGE_OVER_MODE = 'SFE_State_ChangeOverMode'
    STATE_FAN_MODE = 'SFE_State_FanMode'
    STATE_FAN_SPEED = 'SFE_State_FanSpeed'
    STATE_FAN_SPEED_3V = 'SFE_State_FanSpeed3V'
    STATE_FORCED_ON_TIME = 'SFE_State_ForcedOnTime'
    STATE_GLOBAL_ACTIVE_POWER_CONSUMPTION = 'SFE_State_GlobalActivePowerConsumption'
    STATE_GLOBAL_THRESHOLD = 'SFE_State_GlobalThreshold'
    STATE_HVAC_MODE = 'SFE_State_HVACMode'
    STATE_LINE1_THRESHOLD = 'SFE_State_Line1Threshold'
    STATE_LINE2_THRESHOLD = 'SFE_State_Line2Threshold'
    STATE_LINE3_THRESHOLD = 'SFE_State_Line3Threshold'
    STATE_LOAD = 'SFE_State_Load'
    STATE_LOADS_PRIORITY = 'SFE_State_LoadsPriority'
    STATE_OFF_BEHAVIOUR = 'SFE_State_OffBehaviour'
    STATE_ON_BEHAVIOUR = 'SFE_State_OnBehaviour'
    STATE_ON_OFF = 'SFE_State_OnOff'
    STATE_OUT_STATUS = 'SFE_State_OutStatus'
    STATE_SHUTTER = 'SFE_State_Shutter'
    STATE_TIMED_MANUAL = 'SFE_State_TimedManual'
    STATE_HUMIDITY = 'SFE_State_Humidity'
    STATE_HUMIDITY_SETPOINT = 'SFE_State_HumiditySetpoint'